name: CI (GPU)

concurrency:
  group: ci-gpu-on-${{ github.event_name }}-from-${{ github.ref_name }}
  cancel-in-progress: true

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      options: -u root
      image: rapidsai/devcontainers:23.06-cpp-cuda11.8-mambaforge-ubuntu22.04
      env:
        DEFAULT_CONDA_ENV: legate
        PYTHONDONTWRITEBYTECODE: 1
        SCCACHE_REGION: us-east-2
        SCCACHE_BUCKET: rapids-sccache-devs
        SCCACHE_S3_KEY_PREFIX: legate-cunumeric-dev
        VAULT_HOST: https://vault.ops.k8s.rapids.ai
        GA_TOKEN: "${{secrets.GITHUB_TOKEN}}"
        GH_TOKEN: "${{secrets.PERSONAL_ACCESS_TOKEN}}"
    steps:
      - name: Build
        shell: bash -eo pipefail {0}
        run: |

          echo "Action token:";
          GITHUB_TOKEN= GH_TOKEN=${GA_TOKEN} gh auth status || true;

          echo "Custom token:";
          GITHUB_TOKEN= GH_TOKEN=${GH_TOKEN} gh auth status || true;

          git clone https://github.com/trxcllnt/legate-separate-build-scripts.git /tmp/repo;
          mv /tmp/repo/home/coder/.{local,gitconfig} /home/coder/;
          chown -R coder:coder /home/coder/;
          chmod a+x /home/coder/.local/bin/*;
          rm -rf /tmp/repo;

          su - coder -c "\
          GITHUB_TOKEN= GH_TOKEN=${GH_TOKEN} \
            ~/.local/bin/entrypoint build-all";
