name: CI (GPU)

concurrency:
  group: ci-gpu-on-${{ github.event_name }}-from-${{ github.ref_name }}
  cancel-in-progress: true

on:
  workflow_dispatch:

jobs:
  build:
    permissions: read-all
    runs-on: ubuntu-latest
    container:
      options: -u root
      image: rapidsai/devcontainers:23.06-cpp-cuda11.8-mambaforge-ubuntu22.04
      env:
        DEFAULT_CONDA_ENV: legate
        PYTHONDONTWRITEBYTECODE: 1
        SCCACHE_REGION: us-east-2
        SCCACHE_BUCKET: rapids-sccache-devs
        SCCACHE_S3_KEY_PREFIX: legate-cunumeric-dev
        VAULT_HOST: https://vault.ops.k8s.rapids.ai
        GH_TOKEN: "${{ secrets.PERSONAL_ACCESS_TOKEN }}"
        GITHUB_TOKEN: "${{ secrets.PERSONAL_ACCESS_TOKEN }}"
    steps:
      - name: Build
        shell: bash -eo pipefail {0}
        run: |
          apt update;
          DEBIAN_FRONTEND=noninteractive \
          apt install -y --no-install-recommends \
              numactl rlwrap;

          git clone https://github.com/trxcllnt/legate-separate-build-scripts.git /tmp/repo;
          mv /tmp/repo/home/coder/.gitconfig /home/coder/.gitconfig;
          mv /tmp/repo/home/coder/.local /home/coder/.local;
          chmod a+x /home/coder/.local/bin/*;
          chown -R coder:coder /home/coder/;
          rm -rf /tmp/repo;

          exec sudo -iu coder --preserve-env=\
          GH_TOKEN,\
          VAULT_HOST,\
          SCCACHE_REGION,\
          SCCACHE_BUCKET,\
          SCCACHE_S3_KEY_PREFIX,\
          DEFAULT_CONDA_ENV,\
          PYTHONDONTWRITEBYTECODE \
          /home/coder/.local/bin/entrypoint \
            bash -i build-all;
