name: Test

concurrency:
  group: pr-on-${{ github.event_name }}-from-${{ github.ref_name }}
  cancel-in-progress: true

on:
  pull_request_target:

jobs:
  build:
    permissions: read-all
    runs-on: ubuntu-latest
    container:
      options: -u root
      image: pauletaylor/devcontainers:23.06-cpp-cuda11.8-mambaforge-ubuntu22.04
      env:
        JOBS: 1
        CMAKE_BUILD_PARALLEL_LEVEL: 1
        PYTHONDONTWRITEBYTECODE: 1
        SCCACHE_REGION: us-east-2
        SCCACHE_BUCKET: rapids-sccache-devs
        SCCACHE_S3_KEY_PREFIX: legate-cunumeric-dev
        VAULT_HOST: https://vault.ops.k8s.rapids.ai
        GH_TOKEN: "${{ secrets.PERSONAL_ACCESS_TOKEN || secrets.GITHUB_TOKEN }}"
        GITHUB_TOKEN: "${{ secrets.PERSONAL_ACCESS_TOKEN || secrets.GITHUB_TOKEN }}"
    steps:

      - name: Clone
        uses: actions/checkout@v3
        with:
          path: repo
          persist-credentials: false
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Setup
        shell: bash --noprofile --norc -x -eo pipefail {0}
        run: |
          echo "pwd: $(pwd)";
          echo "uid: $(whoami) $(id -u):$(id -g)";
          echo "env:";
          env;
          ls -all .;

          mv repo/home/coder/.local/bin /home/coder/.local/bin;
          mv repo/home/coder/.gitconfig /home/coder/.gitconfig;
          chmod +x /home/coder/.local/bin/*;
          chown -R coder:coder /home/coder/;
          rm -rf repo;

          apt update;
          DEBIAN_FRONTEND=noninteractive \
          apt install -y --no-install-recommends \
              numactl rlwrap;


      - name: Build
        shell: su coder -Pc 'bash -lix {0}'
        run: |
          echo "pwd: $(pwd)";
          echo "uid: $(whoami) $(id -u):$(id -g)";
          echo "env:";
          env;
          ls -all .;
